build:
  script:
  - cd /media/storage/gitlab/
  after_script:
  - cd /media/storage/gitlab/
  - sudo rm -rf raspbian-cmake-toolchains
  - git clone http://192.168.109.15/root/raspbian-cmake-toolchains.git
