build:
  script:
  - cd /media/storage/gitlab/
  after_script:
  - cd /media/storage/gitlab/
  - sudo rm -rf raspbian-cmake-toolchains
  - git clone http://git.home.lan/root/raspbian-cmake-toolchains.git
