set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ARM)
set(CMAKE_LIBRARY_ARCHITECTURE arm-linux-gnueabihf)

set(RASPBIAN_TOOLCHAIN_DIR "/home/orfanidi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/")
set(TOOLCHAIN_PREFIX arm-linux-gnueabihf-)

if(${CMAKE_VERSION} VERSION_LESS 3.6.0)
    include(CMakeForceCompiler)
    CMAKE_FORCE_C_COMPILER(${RASPBIAN_TOOLCHAIN_DIR}${TOOLCHAIN_PREFIX}gcc GNU)
    CMAKE_FORCE_CXX_COMPILER(${RASPBIAN_TOOLCHAIN_DIR}${TOOLCHAIN_PREFIX}g++ GNU)
else()
  set(CMAKE_C_COMPILER ${RASPBIAN_TOOLCHAIN_DIR}${TOOLCHAIN_PREFIX}gcc CACHE PATH "")
  set(CMAKE_CXX_COMPILER ${RASPBIAN_TOOLCHAIN_DIR}${TOOLCHAIN_PREFIX}g++ CACHE PATH "")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
